apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml

images:
- name: PROJECT/BROADCAST
  newName: europe-north1-docker.pkg.dev/dwk-gke-123456/broadcast-repo/broadcast
  newTag: main-e4f983d862557b026d6e2b49ebd42f3bafc0b352
