apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml

images:
- name: PROJECT/BROADCAST
  newName: europe-north1-docker.pkg.dev/dwk-gke-123456/broadcast-repo/broadcast
  newTag: main-ef88d45c5b642d6259a6850a50c7cbaea3c0fd3b
