apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- manifests/config.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/pvc.yaml
- manifests/gateway.yaml
- manifests/route.yaml
images:
- name: PROJECT/FRONTEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-123456/frontend-repo/frontend-todo
  newTag: main-8ac51426c46faa3b5b185f517b33d38cdaa98f3e
