apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- manifests/config.yaml
- manifests/deployment.yaml
- manifests/service.yaml
- manifests/pvc.yaml
- manifests/gateway.yaml
- manifests/route.yaml
images:
- name: PROJECT/FRONTEND
  newName: europe-north1-docker.pkg.dev/dwk-gke-123456/frontend-repo/frontend-todo
  newTag: main-9466e2abe78a354f762b991cf46c7a329c559807
