apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests 

vars:
  - name: DB_SERVICE
    objref:
      kind: Service
      name: project-postgres-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
