name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  BACKEND_REPO: backend-repo
  FRONTEND_REPO: frontend-repo
  BACKEND_IMAGE: backend-todo
  FRONTEND_IMAGE: frontend-todo
  BACKEND_DEPLOY: backend-deployment
  FRONTEND_DEPLOY: project-dep
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Google Cloud auth
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 3. Enable Artifact Registry auth
      - name: Configure Artifact Registry
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      # 4. Connect to GKE
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      # 5. Form image names
      - name: Form backend image tag
        run: echo "BACKEND_TAG=$REGISTRY/$PROJECT_ID/$BACKEND_REPO/$BACKEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Form frontend image tag
        run: echo "FRONTEND_TAG=$REGISTRY/$PROJECT_ID/$FRONTEND_REPO/$FRONTEND_IMAGE:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      # 6. Build images
      - name: Build backend image
        run: docker build ./Project/Backend_todo -t $BACKEND_TAG

      - name: Build frontend image
        run: docker build ./Project/Frontend_todo -t $FRONTEND_TAG

      # 7. Push images
      - name: Push backend
        run: docker push $BACKEND_TAG

      - name: Push frontend
        run: docker push $FRONTEND_TAG

      # 8. Kustomize setup
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      # 9. Deploy backend
      - name: Deploy backend
        run: |
          cd Project/Backend_todo
          kustomize edit set image PROJECT/BACKEND=$BACKEND_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $BACKEND_DEPLOY -n project

      # 10. Deploy frontend
      - name: Deploy frontend
        run: |
          cd Project/Frontend_todo
          kustomize edit set image PROJECT/FRONTEND=$FRONTEND_TAG
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $FRONTEND_DEPLOY -n project

      # 11. Show services
      - name: Show services
        run: kubectl get svc -n project -o wide

