apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: project
spec: # deployments selector
  selector:
    matchLabels:
      app: backend 
  template: #pods template labels must match with deployments selector
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: matiashonkasalo/backend:1.12
        ports:
          - containerPort: 3002

