apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: project
spec: # deployments selector
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template: #pods template labels must match with deployments selector
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: PROJECT/BACKEND
        env: 
          - name: PORT
            value: "3002"
          - name: POSTGRES_URL
            value: postgres://postgres:example@project-postgres-service:5432/project
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "150Mi"


